
# CUDA_VISIBLE_DEVICES=6,7,8,9 python -m torch.distributed.launch --nproc_per_node 4 --master_port 2478 train.py -opt /data_video/code/SelfC/selfc_framework/codes/options/train_v2/rescaling/train_SelfC_large_GMM_STP6.yml --launcher pytorch

#### general settings

name: SelfC_large_GMM_STP6
use_tb_logger: true
model: SelfC_GMM
distortion: sr_bd
scale: 4

# gpu_ids: [0]
gpu_ids: [2,3]


#### datasets

datasets:
  train:
    name: VIMEO90k
    mode: LQGTVID
    dataroot_GT: /data_video/vimeo90k/vimeo90k/vimeo_septuplet/sequences # path to training HR images
    dataroot_list: /data_video/vimeo90k/vimeo90k/vimeo_septuplet/sep_trainlist.txt # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    video_len: 7
    use_shuffle: true
    n_workers: 2  # per GPU
    batch_size: 4
    GT_size: 224
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: city
    val_batch_size: 1
    mode: LQGTVID
    dataroot_GT: /data_video/videoSR/city/ds_7_to_7 # path to validation HR images
    dataroot_list: /data_video/videoSR/city/ds_7_to_7/testlist.txt  # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    video_len: 7
    

#### network structures

network_G:
  which_model_G:
      subnet_type: D2DTNet
  in_nc: 3
  out_nc: 3
  block_num: [4, 4]
  scale: 4
  init: xavier
  global_module: nonlocal
  stp_blk_num: 6
  fh_loss: gmm
  gmm_k: 5
  # stp_d2d_inner_c: 32
  # stp_temporal_c: 32
  # stp_blk_num: 6
  # fh_loss: l2
  



#### path

path:
  pretrain_model_G: 
  strict_load: 
  resume_state: 



#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 1e-4
  beta1: 0.9
  beta2: 0.999
  niter: 400000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [100000, 200000,300000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  lambda_cond_prob: 0
  lambda_gaussian_reg: 0

  manual_seed: 10

  val_freq: !!float 1e4

  lambda_fit_forw: 1
  lambda_rec_back: 1
  lambda_ce_forw: 1
  weight_decay_G: !!float 1e-14
  gradient_clipping: 10


#### logger

logger:
  print_freq: 10
  save_checkpoint_freq: !!float 2e4
